### ISSUE TITLE
how to change the location 

### ISSUE THREAD

**Issue by Khnaz35** [dsottimano/dsottimano-google-cli-for-seos#1]
Hi, Thanks for the tool, 
Just a quick question how to change the location to my preferred location ?
param: '&gl=es&hl=es&lr=lang_es&uule=w+CAIQICIMbWFkcmlkIHNwYWlu',
Where can i find the list of this query

**Comment by dsottimano** [comment]
Right here https://github.com/dsottimano/dsottimano-google-cli-for-seos/blob/6f633ebc63aab64cf4f3358a7d0465b1bd0bd0dd/main.js#L177

You'll have to change the UULE code, to find it use: https://site-analyzer.pro/services-seo/uule/
